### ISSUE TITLE
gedit aborts with core dump when trying to use markdown

### ISSUE THREAD

**Issue by KCulture** [darkdragon-001/gedit-markdown#2]
@darkdragon-001 
I am using gedit 3.28.1 in ubuntu 18.04 all seems to work okay until I try to use markdown feature Toggle Markdown Preview visibility. At this point the gedit crashes with an abort core dump. I am not able to view any logs so that is the limited information that I have.. 

information about software I have installed
Ubuntu 18.04
gedit 3.28.1
gir1.2-webkit-4.0
python3-markdown

I didn't not install the recommended PyMdown Extensions because I am not interested in installing pip.

**Comment by darkdragon-001** [comment]
What is your config `~/.config/gedit/markdown-preview/preferences.ini`?

You can start `gedit` from the console. There should be a stack trace printed to the console when a core dump occurs.

**Comment by InonS** [comment]
Reproduceable on `master`.

Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/latex/tabdecorator.py", line 87, in _on_load
    self._adjust_editor()
  File "/usr/lib/gedit/plugins/latex/tabdecorator.py", line 107, in _adjust_editor
    location = self._text_buffer.get_location()
AttributeError: 'Document' object has no attribute 'get_location'
Aborted (core dumped)
```
Preference file:
```
$ cat ~/.config/gedit/markdown-preview/preferences.ini 
[markdown-preview]
panel = bottom
shortcut = <Control><Alt>m
extensions = extra toc
visibility = 0
visibilityShortcut = <Control><Alt>v
autoIdle = 250
autoReloadActivate = 1
autoReloadOpen = 1
autoReloadSave = 1
autoReloadTabs = 0
autoReloadEdit = 1
autoReloadSelection = 0
```
System:
Ubuntu 20.04
```
$ gedit --version
gedit - Version 3.36.2
```
gir1.2-webkit2-4.0
python3-markdown/focal,focal,now 3.1.1-3 all

**Comment by KCulture** [comment]
unfortunately I only got Aborted (core dumped) in my console

**Comment by darkdragon-001** [comment]
The original repo (https://github.com/jpfleury/gedit-markdown) came back to live and was updated for newer versions of gedit. Please try again and report potential issues there.
